[package]
name = "patina"
version = "0.1.0"
edition = "2021"
authors = ["Alec Nunn <alec.nunn@gmail.com>"]

[dependencies]
object = "0.37"
goblin = "0.10"
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
regex = "1.10"
colored = "3.0"
